
#security:
#  oauth2:
#    resource:
#       userInfoUri: http://localhost:8901/auth/user   # 콜백 URL
#       token-type: Bearer

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: DEBUG
    com.thoughtmechanix: DEBUG


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
