management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: DEBUG
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

# 차단 목록 리스트 -> 디폴트 [Cookie, Set-Cookie, Authorization]
# 아래 처럼 설정해야 Authorization 헤더를 하위서비스(라이선싱, 조직)에 토큰 전파가 가능해짐
zuul:
  sensitive-headers: Cookie,Set-Cookie

#
#
#  debug:
#    request: true
#
#zuul:
#  prefix:  /api
#  routes:
#    organizationservice: /organization/**
#    licensingservice: /licensing/**

