version: '3.0'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr@s
      PSTGRES_DB: eagle_eye_local
    ports:
    - 5432:5432
    container_name: postgres-msa
  redis:
    image: redis
    ports:
    - 6379:6379
    container_name: redis-msa



