version: '3.0'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr@s
      POSTGRES_DB: eagle_eye_local
    ports:
      - 5432:5432
    container_name: postgres-msa

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis-msa

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper-msa

  kafka:
    image: spotify/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    container_name: kafka-msa
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock