spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/jpashop1
    username: ssosso
    password: ssosso
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
